## Yarn 3 cache does not work out of the box as of Jan 2022. Context:
## https://github.com/netlify/build/issues/1535#issuecomment-1021947989
[build.environment]
NETLIFY_USE_YARN = "true"
YARN_ENABLE_GLOBAL_CACHE = "true"
YARN_CACHE_FOLDER = "/opt/buildhome/node_modules"
YARN_VERSION = "3.1.1"
