
[profile.default]
src = 'src'
out = 'out'
libs = ['../node_modules', 'lib']

[rpc_endpoints]
arbitrumGoerli = "https://goerli-rollup.arbitrum.io/rpc"
arbitrum = "https://arb1.arbitrum.io/rpc"
goerli = "https://goerli.infura.io/v3/${process.env.INFURA_API_KEY}"
mainnet = "https://mainnet.infura.io/v3/${process.env.INFURA_API_KEY}"
chiado = "https://rpc.chiadochain.net"
gnosischain = "https://xdai-rpc.gateway.pokt.network"

# See more config options https://book.getfoundry.sh/reference/config.html
