on:
  pull_request:
    types: [opened]

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    name: Copy labels from linked issues
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.5.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            yarnpkg.com:443
            github.com:443
            nightly.yarnpkg.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            registry.yarnpkg.com:443
            registry.npmjs.org:443

      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
